print("           WELCOME TO MARK CALCULATING MACHINE")
name = str(input(" enter student name | "))
E = float(input("enter english mark = "))
M = float(input("enter math mark  = "))
I = float(input("enter I.R.K mark = "))
H = float(input("enter hausa mark = "))
A = float(input("enter arabic merk = "))
S = float(input("enter sos mark = "))
A= float(input("enter Art mark = "))
AG = float(input("enter Agric mark = "))
Totalmark =(E+M+I+H+A+S+AG)
print("Total mark for", name,' is',Totalmark)